### PR TITLE
web3mail whitelist

### PR DESCRIPTION
**Pull request by greg-szrama**
Documentation for PRO-531, for web3mailApplicationWhitelist method

### CODE REVIEW

**Review by Le-Caignec — CHANGES_REQUESTED** [review]
It's not a method, it's a different value that can be put in the `dataProtector.grantAccess` method for the use of web3mail-sdk. I don't know where is the best way to put that, may be in dataprotector-sdk as it's for the `grantAccess` method. Nevertheless, it' was added in dataprotector-sdk specifitly to make web3mail-sdk easier (eliminating the need to repeat the process whenever an application is updated)

**Comment by Le-Caignec** [comment]
May be the best way to do that should be to include an explanation within the `dataProtector.grantAccess` method, informing users that when they grant access to a specific method, they should re-execute the function if the Dapp is upgraded and if they want to have the last version.

A simple and scalable solution for users would be to grant access to a whitelist. This strategy has been implemented for the web3mail Dapp (each Dapp should have it's own whitelist), where we have developed a whitelist for the community. For more details => redirect users to the web3mail-sdk whitelist documentation ...

**Comment by greg-szrama** [comment]
@Le-Caignec , I'm looking at this and the whitelist address from the issue:

const web3mailApplicationWhitelist= "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e";

Is the same address used in the DataProtector grantAccess method:

authorizedApp: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',

Is this intentional?

**Comment by Le-Caignec** [comment]
yeah it's intentional because the authorizedApp here is a list of application (the whitelist)

**Comment by greg-szrama** [comment]
Closing this PR, I'll address this issue in the refactor stage one branch.

**Pull request closed without merging**
